# Generated by Django 2.2.6 on 2019-10-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('shop_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategoryPages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('shop_id', models.IntegerField()),
                ('img_url', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
