# Generated by Django 2.2.6 on 2019-10-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorylinks',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='productcategorypages',
            name='url',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
