# Generated by Django 2.2.6 on 2019-10-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_links', '0003_auto_20191015_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategorypages',
            name='price',
            field=models.TextField(),
        ),
    ]
